exports.WITHDRAW_REQUEST_STATUS = {
  REQUESTED: 'REQUESTED',
  APPROVED: 'APPROVED',
  DECLINED: 'DECLINED',
  PROCESSED: 'PROCESSED'
};

exports.SHOP_TYPE = {
  RESTAURANT: 'RESTAURANT',
  GROCERY: 'GROCERY',
  PHARMACY: 'PHARMACY'
};

exports.BANNER_ACTIONS = {
  CUISINE: 'CUISINE',
  RESTAURANT: 'RESTAURANT',
  LINK: 'LINK',
  NONE: 'NONE'
};

exports.ORDER_STATUS = {
  PENDING: 'PENDING',
  ACCEPTED: 'ACCEPTED',
  PICKED: 'PICKED',
  DELIVERED: 'DELIVERED',
  CANCELLED: 'CANCELLED',
  COMPLETED: 'COMPLETED'
};

exports.order_status = [
  'PENDING',
  'ACCEPTED',
  'PICKED',
  'DELIVERED',
  'CANCELLED',
  'COMPLETED'
];

exports.payment_status = [
  'PENDING',
  'PAID',
  'FAILED'
];
