exports.WITHDRAW_REQUEST_STATUS = {
  REQUESTED: 'REQUESTED',
  APPROVED: 'APPROVED',
  DECLINED: 'DECLINED',
  PROCESSED: 'PROCESSED'
};

exports.SHOP_TYPE = {
  RESTAURANT: 'RESTAURANT',
  GROCERY: 'GROCERY',
  PHARMACY: 'PHARMACY'
};

exports.BANNER_ACTIONS = {
  CUISINE: 'CUISINE',
  RESTAURANT: 'RESTAURANT',
  LINK: 'LINK',
  NONE: 'NONE'
};
