const PLACE_ORDER = "PLACE_ORDER";
const ORDER_STATUS_CHANGED = "ORDER_STATUS_CHANGED";
const EDIT_ORDER = "EDIT_ORDER";
const RIDER_UPDATED = "RIDER_UPDATED";
const RIDER_ASSIGNED = "RIDER_ASSIGNED";
const SUBSCRIPTION_ORDER = "SUBSCRIPTION_ORDER";
module.exports = {
  PLACE_ORDER,
  ORDER_STATUS_CHANGED,
  EDIT_ORDER,
  RIDER_UPDATED,
  RIDER_ASSIGNED,
  SUBSCRIPTION_ORDER,
};
