const PLACE_ORDER = "PLACE_ORDER";
const ORDER_UPDATED = "ORDER_UPDATED";
const SUBSCRIPTION_ORDER = "SUBSCRIPTION_ORDER";

module.exports = {
  PLACE_ORDER,
  ORDER_UPDATED,
  SUBSCRIPTION_ORDER
};

