import mongoose from 'mongoose';

const ConfigurationSchema = new mongoose.Schema({
  email: String,
  emailName: String,
  password: String,
  enableEmail: Boolean,
  formEmail: String,
  sendGridApiKey: String,
  sendGridEnabled: Boolean,
  sendGridEmail: String,
  sendGridEmailName: String,
  sendGridPassword: String,
  firebaseKey: String,
  authDomain: String,
  projectId: String,
  storageBucket: String,
  msgSenderId: String,
  appId: String,
  measurementId: String,
  vapidKey: String,
  dashboardSentryUrl: String,
  webSentryUrl: String,
  apiSentryUrl: String,
  customerAppSentryUrl: String,
  restaurantAppSentryUrl: String,
  riderAppSentryUrl: String,
  googleApiKey: String,
  cloudinaryUploadUrl: String,
  cloudinaryApiKey: String,
  webAmplitudeApiKey: String,
  appAmplitudeApiKey: String,
  webClientID: String,
  androidClientID: String,
  iOSClientID: String,
  expoClientID: String,
  googleMapLibraries: String,
  googleColor: String,
  termsAndConditions: String,
  privacyPolicy: String,
  testOtp: String,
  deliveryRate: Number,
  costType: String,
  clientId: String,
  clientSecret: String,
  sandbox: Boolean,
  publishableKey: String,
  secretKey: String,
  twilioAccountSid: String,
  twilioAuthToken: String,
  twilioPhoneNumber: String,
  twilioEnabled: Boolean,
  skipEmailVerification: Boolean,
  skipMobileVerification: Boolean,
  currency: String,
  currencySymbol: String,
});

export default mongoose.model('Configuration', ConfigurationSchema);